{-
   This file was automatically generated by elm-graphql.
-}


module GraphQL.Blog exposing (usersRequest, loginRequest, Users, User, Token)

import Json.Decode exposing (..)
import Json.Encode exposing (encode)
import Http
import GraphQL exposing (apply, maybeEncode)


endpointUrl : String
endpointUrl =
    "http://localhost:4000/api/"



-- TYPES


type alias User =
    { name : String
    , email : String
    }


type alias Users =
    List User


type alias Token =
    { token : Maybe String
    , errors : Maybe (List String)
    }



-- REQUESTS


usersRequest : Http.Request Users
usersRequest =
    let
        graphQLQuery =
            """query users { users { name, email } }"""
    in
        let
            graphQLParams =
                Json.Encode.object
                    []
        in
            GraphQL.query "POST" endpointUrl graphQLQuery "users" graphQLParams usersDecoder


loginRequest : String -> String -> Http.Request Token
loginRequest email password =
    let
        graphQLQuery =
            """
                mutation Login($email: String, $password: String) {
                    login(email: $email, password: $password){
                        token
                    }
                }
            """
    in
        let
            graphQLParams =
                Json.Encode.object
                    [ ( "email", Json.Encode.string email )
                    , ( "password", Json.Encode.string password )
                    ]
        in
            GraphQL.mutation endpointUrl graphQLQuery "Login" graphQLParams tokenDecoder



-- DECODERS


usersDecoder : Decoder Users
usersDecoder =
    (at [ "data", "users" ] (list userDecoder))


userDecoder : Decoder User
userDecoder =
    map2 User
        (field "name" string)
        (field "email" string)


tokenDecoder : Decoder Token
tokenDecoder =
    map2 Token
        (maybe (at [ "data", "login", "token" ] string))
        (maybe (at [ "errors" ] (list errorDecoder)))


errorDecoder : Decoder String
errorDecoder =
    (field "message" string)
